parameters:
- name: image
  displayName: Pool Image
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest

- name: test
  displayName: Run Tests?
  type: boolean
  default: false

- name: Pokemon
  type: string
  default: pikachu
  values:
  - Bulbasaur
  - Ivysaur
  - Venusaur
  - Charmander
  - Charmeleon
  - Charizard
  - Squirtle
  - Wartortle
  - Blastoise
  - Caterpie
  - Metapod
  - Butterfree
  - Weedle
  - Kakuna
  - Beedrill
  - Pidgey
  - Pidgeotto
  - Pidgeot
  - Rattata
  - Raticat
  - Spearow
  - Fearow
  - Ekans
  - Arbok
  - Pikachu
  - Raichu
  - Sandshrew
  - Sandslash
  - Nidoran♀
  - Nidorina
  - Nidoqueen
  - Nidoran♂
  - Nidorino
  - Nidoking
  - Clefairy
  - Clefable
  - Vulpix
  - Ninetales
  - Jigglypuff
  - Wigglytuff
  - Zubat
  - Golbat
  - Oddish
  - Gloom
  - Vileplume
  - Paras
  - Parasect
  - Venonat
  - Venomoth
  - Diglett
  - Dugtrio
  - Meowth
  - Persian
  - Psyduck
  - Golduc
  - kMankey
  - Primeape
  - Growlithe
  - Arcanine
  - Poliwag
  - Poliwhirl
  - Poliwrath
  - Abra
  - Kadabra
  - Alakazam
  - Machop
  - Machoke
  - Machamp
  - Bellsprout
  - Weepinbell
  - Victreebel
  - Tentacool
  - Tentacruel
  - Geodude
  - Graveler
  - Golem
  - Ponyta
  - Rapidash
  - Slowpoke
  - Slowbro
  - Magnemite
  - Magneton
  - Farfetch'd
  - Doduo
  - Dodrio
  - Seel
  - Dewgong
  - Grimer
  - Muk
  - Shellder
  - Cloyster
  - Gastly
  - Haunter
  - Gengar
  - Onix
  - Drowzee
  - Hypno
  - Krabby
  - Kingler
  - Voltorb
  - Electrode
  - Exeggcute
  - Exeggutor
  - Cubone
  - Marowak
  - Hitmonlee
  - Hitmonchan
  - Lickitung
  - Koffing
  - Weezing
  - Rhyhorn
  - Rhydon
  - Chansey
  - Tangela
  - Kangaskhan
  - Horsea
  - Seadra
  - Goldeen
  - Seaking
  - Staryu
  - Starmie
  - Mr. Mime
  - Scyther
  - Jynx
  - Electabuzz
  - Magmar
  - Pinsir
  - Tauros
  - Magikarp
  - Gyarados
  - Lapras
  - Ditto
  - Eevee
  - Vaporeon
  - Jolteon
  - Flareon
  - Porygon
  - Omanyte
  - Omastar
  - Kabuto
  - Kabutops
  - Aerodactyl
  - Snorlax
  - Articuno
  - Zapdos
  - Moltres
  - Dratini
  - Dragonair
  - Dragonite
  - Mewtwo
  - Mew

trigger:
  branches:
    include:
    - main

stages:
  - stage: Dex
    condition:
    jobs:
    - job: build
      displayName: Build and Test
      pool: 
        vmImage: ${{ parameters.image }}
      steps:
      - script: echo building $(Build.BuildNumber)
      - ${{ if eq(parameters.test, true) }}:
        - script: echo running test file
        - task: PowerShell@2
          inputs:
            targetType: filePath
            filePath: test.ps1
    - job: GeneratePokedexEntry
      displayName: Generate Pokedex Entry
      pool: 
        vmImage: ${{ parameters.image }}
      workspace:
        clean: all
      steps:
        - checkout: self
          fetchDepth: 1
        - script: echo "You picked ${{Parameters.Pokemon}}"
        - task: PowerShell@2
          inputs:
            targetType: filePath
            filePath: CreatePokedexEntry.ps1
            arguments: -pokemonName ${{ parameters.Pokemon }}
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: Entries'
          inputs:
            pathToPublish: Entries
            publishLocation: Container
            artifactName: "Entries"
            targetPath: '$(Pipeline.Workspace)'